config/routes.rb
Rails.application.routes.draw do
  resources :games

  root 'games#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many  :shots, validate: true
  validates :players, numericality: { greater_than: 0, less_than: 5 }
  accepts_nested_attributes_for :shots
end

app/models/shot.rb
class Shot < ApplicationRecord
  belongs_to :game
  validates :number, :frame, :player, :pins, numericality: true
  validate :number_of_pins

  def number_of_pins
    current_pins = pins.to_i
    if current_pins > 10
      return errors.add(:pins, "can't be more than 10")
    elsif current_pins < 0
        errors.add(:pins, "cannot be less than zero")
    elsif frame < 10
      shots = current_player_frame
      existing_pins = shots.map(&:pins).reduce(0, :+)
      if (existing_pins + current_pins) > 10
        max = 10 - existing_pins
        errors.add(:pins, "can't be more than #{max}")
      end
    else
      shots = current_player_frame
      if shots.size > 1 && shots[0].pins < 10
        if (shots[0].pins + shots[1].pins) > 10
          errors.add(:pins, "can't be more than 10")
        end
      end
    end
  end

  private
  def current_player_frame
    Shot.where(game: game,
               player: player,
               frame: frame).order(:number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
    @shot = @game.shots.build
    @scoreboard = ScoreBoardPresenter.new(@game)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        session[:frame] = session[:player] = session[:shot_number] = 1
        session[:game_over] = session[:strike] = session[:spare] = false
        format.html { redirect_to @game, notice: 'Welcome to the game!' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        @scoreboard = ScoreBoardPresenter.new(@game)
        last_shot    = @game.shots.last
        current_game = ::GameEngine.new(@game, session)
        current_game.update(last_shot)
        session.merge!(current_game.status)

        format.html { redirect_to @game, notice: 'Scores were successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        @shot = @game.shots.last
        @scoreboard = ScoreBoardPresenter.new(@game)
        format.js { render 'errors' }
        format.html { render :show, notice: 'Scores were not successfully updated.' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:players, shots_attributes: [:number, :frame, :player, :pins])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :players, class: 'sr-only' %>
    <%= f.number_field :players , class: 'form-control', placeholder: 'Number of Players' %>
  </div>

  <div class="actions form-group">
    <%= f.submit "Start", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/games/_new_shot.html.erb
<div id='shot-form'>
  <%= form_for(@game, remote: true, authenticity_token: true, html: { class: 'form-inline'}) do |f| %>
    <%= f.fields_for :shots, @shot do |shot| %>
      <% if @shot.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

          <ul>
            <% @game.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= shot.hidden_field :player, value: session[:player] %>
      <%= shot.hidden_field :frame, value: session[:frame] %>
      <%= shot.hidden_field :number, value: session[:shot_number] %>
      <div class='row'>
        <div class='col-xs-12 col-md-9 offset-xs-0 offset-md-2 col-lg-8 offset-lg-3'>
          <div class="field form-group">
            <%= shot.label :pins, "Score:", class: 'sr-only' %>
            <%= shot.number_field :pins, class: 'form-control form-control-lg', placeholder: 'Pins down' %>
          </div>
          <%= f.submit "Submit Shot", class: 'btn btn-lg btn-primary' %>
        </div>
      </div>
    <% end %>

  <% end %>
</div>

app/views/games/_score_table.html.erb
<div class='table-responsive'>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>
          &nbsp;
        </th>
        <th>
          Frame 1
        </th>
        <th>
          Frame 2
        </th>
        <th>
          Frame 3
        </th>
        <th>
          Frame 4
        </th>
        <th>
          Frame 5
        </th>
        <th>
          Frame 6
        </th>
        <th>
          Frame 7
        </th>
        <th>
          Frame 8
        </th>
        <th>
          Frame 9
        </th>
        <th>
          Frame 10
        </th>
        <th>
          Total
        </th>
      </tr>
    </thead>
    <tbody>
      <% @scoreboard.scoreboard.each_with_index do |row, i| %>
        <tr>
          <th>
            Player: <%= i+1 %>
          </th>
        <% row[1..10].each do |cell| %>
          <td>
            <b><%= @scoreboard.total_for_frame(cell) %></b>
            <div><%= @scoreboard.first_shot(cell) %></div>
            <div><%= @scoreboard.second_shot(cell) %></div>
            <div><%= @scoreboard.third_shot(cell) %></div>
          </td>
        <% end %>
        <td>
          <%= @scoreboard.grand_total(row) %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/errors.js.erb
$('form').replaceWith('<%= j(render partial: 'new_shot') %>');

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Players</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.players %></td>
        <td><%= link_to 'Show', game %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path, class: 'btn btn-lg btn-primary' %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

<%= opal_tag do %>
  Document.ready? do
    @games_view = GamesView.new
  end
<% end %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<header class='header'>
<div class='row'>
  <div class='col-xs-4'>
    <h1 class='font-italic'><strong>Game:</strong>
    <%= @game.id %></h1>
  </div>
  <div class='col-xs-8'>
    <h1 class='text-xs-right font-italic'>
    <strong>Players:</strong>
    <%= @game.players %>
    </h1>
  </div>
</div>
</header>

<div class='row'>
  <div class='col-xs-4'>
  <section class='card'>
    <header class='card-title'>
      <h4>Current Player</h4>
    </header>
    <div class='card-text'><h1><%= session[:player] %></h1></div>
  </section>
  </div>
  <div class='col-xs-4'>
  <section class='card'>
    <header class='card-title'>
      <h4>Current Frame</h4>
    </header>
    <div class='card-text'><h1><%= session[:frame] %></h1></div>
  </section>
  </div>
  <div class='col-xs-4'>
  <section class='card'>
    <header class='card-title'>
      <h4>Current Shot</h4>
    </header>
    <div class='card-text'><h1><%= session[:shot_number] %></h1></div>
  </section>
  </div>
</div>

<% if session[:strike] %>
    <div class='card-text'><h1>STRIKE!</h1></div>
  <% elsif session[:spare] %>
    <div class='card-text'><h1>SPARE!</h1></div>
  <% elsif session[:game_over] %>
    <div class='card-text'><h1>GAME OVER!</h1></div>
<% end %>

<%= render partial: 'new_shot' unless session[:game_over] %>
<%= render partial: 'score_table' %>

<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TenPinBowling</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %> container'>
    <%= yield %>
  </body>
</html>